version: "3.9"

services:
  app:
    container_name: app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
      - JWT_SECRET=${JWT_SECRET}
    build:
      context: .
    ports:
      - 3500:3500
